export const testomonail = [
  {
    id: 1,
    myname:'My name is',
    fname: 'Masooma Mohammadi',
    img: 'images/masooma.jpg',
    phone: '0786516353',
    job: 'Web developer',
    email: 'masoomam969@mail.com',
    age: '19',
    password:'masoomam251',
  },
  {
    id: 2,
    myname:'My name is',
    fname: 'Zarifa Rahmani',
    img: 'images/person-1.jpg',
    phone: '078172072',
    job: 'Business woman',
    email: 'zarifa99@mail.com',
    age: '20',
    password:'Zarifa-@20',
  },
  {
    id: 3,
    myname:'My name is',
    fname: 'Zarafshan Asghri',
    img: 'images/person-4.jpg',
    phone: '0787969878',
    job: 'Web developer',
    email: 'zarafshan77@mail.com',
    age: '21',
    password:'Zarafshan-#44',
  },
  {
    id: 4,
    myname:'My name is',
    fname: 'Masoma Aahmadi',
    img: 'images/person-2.jpg',
    phone: '0785684546',
    job: 'Manager',
    email: 'masooma799@mail.com',
    age: '18',
    password:'masooma-$4657',
  },
  {
    id: 5,
    myname:'My name is',
    fname: 'Shakiba Hiadari',
    img: 'images/person-3.jpg',
    phone: '0705094878',
    job: 'Bass',
    email: 'shakiba457@mail.com',
    age: '21',
    password:'shakiba-@999$',
  },
  {
    id: 6,
    myname:'My name is',
    fname: 'Ziba Mohammadi',
    img: 'images/person-5.jpg',
    phone: '0798089767',
    job: 'We design',
    email: 'ziba38457@mail.com',
    age: '20',
    password:'ziba-20',
  },
  {
    id: 1,
    myname:'My name is',
    fname: 'Mahboba Akhlaqi',
    img: 'images/person-6.jpg',
    phone: '8596-569805034',
    job: 'We developer',
    email: 'mahboba9238457@mail.com',
    age: '22',
    password:'mahboba-@111',
  },
];