export const testomonail = [
  {
    id: 1,
    myname:'My name is',
    fname: 'Ji-Yeon',
    img: 'images/person-7.jpeg',
    phone: '0786516303',
    job: 'Web developer',
    email: 'Ji-Yeon000@mail.com',
    age: '19',
    password:'Ji-Yeon251',
  },
  {
    id: 2,
    myname:'My name is',
    fname: 'Hye-Won',
    img: 'images/person-6.jpeg',
    phone: '078172072',
    job: 'Business woman',
    email: 'Hye-Won99@mail.com',
    age: '20',
    password:'Hye-Won-@20',
  },
  {
    id: 3,
    myname:'My name is',
    fname: 'Soo-Jin',
    img: 'images/person-5.jpeg',
    phone: '0787969878',
    job: 'Web developer',
    email: 'Soo-Jinn77@mail.com',
    age: '21',
    password:'Soo-Jin-#44',
  },
  {
    id: 5,
    myname:'My name is',
    fname: 'Yoo-Jin',
    img: 'images/person-3.jpeg',
    phone: '0705094878',
    job: 'Bass',
    email: 'Yoo-Jin457@mail.com',
    age: '21',
    password:'Yoo-Jin-@999$',
  },
  {
    id: 7,
    myname:'My name is',
    fname: 'Ji-Hye',
    img: 'images/person-1.jpeg',
    phone: '8596-569805034',
    job: 'We developer',
    email: 'Ji-Hye9238457@mail.com',
    age: '22',
    password:'mJi-Hye-@111',
  },
];